export const APP_ROUTES = {
  root: '/',
  handoff: '/auth/handoff',
  finance: '/finance',
  financeSetup: '/finance/setup',
  financeSettings: '/finance/settings',
  financeSettingsAccounts: '/finance/settings/accounts',
  financeSettingsEntities: '/finance/settings/entities',
  financeSettingsFunds: '/finance/settings/funds',
  financeSettingsCategories: '/finance/settings/categories',
  count: '/finance/count',
  balance: '/finance/balance',
  inbox: '/finance/inbox',
  reports: '/finance/reports',
  audit: '/finance/audit',
  more: '/finance/more',
  transactions: '/finance/transactions',
  transactionCreate: '/finance/transactions/new',
  transactionDetail: '/finance/transactions/:transactionId',
  transactionEdit: '/finance/transactions/:transactionId/edit',
  review: '/finance/review',
  financeReview: '/finance/review',
  transactionReviewDetail: '/finance/review/:transactionId',
  accessDenied: '/access-denied',
  unavailable: '/unavailable',
  preview: '/__preview/foundation',
} as const;
