export const APP_ROUTES = {
  root: '/',
  handoff: '/auth/handoff',
  finance: '/finance',
  financeSetup: '/finance/setup',
  count: '/finance/count',
  balance: '/finance/balance',
  inbox: '/finance/inbox',
  reports: '/finance/reports',
  audit: '/finance/audit',
  more: '/finance/more',
  accessDenied: '/access-denied',
  unavailable: '/unavailable',
  preview: '/__preview/foundation',
} as const;
