import type { Language } from '@/src/contexts/LanguageContext';

export const COUNT_CAPTURE_COPY: Record<Language, any> = {
  PT: {
    title: 'Capturar Folha Count',
    subtitle: 'Fotografe ou escolha a folha preenchida. O original é preservado e a conferência continua humana.',
    choosePhoto: 'Escolher foto',
    camera: 'Usar câmera',
    replace: 'Trocar imagem',
    processing: 'Preparando imagem…',
    detectedQr: 'Folha identificada pelo QR',
    manualReference: 'Referência da folha',
    manualReferenceHint: 'Se o QR não for reconhecido, digite a referência cpf_… impressa na folha.',
    upload: 'Enviar para conferência',
    uploading: 'Enviando com segurança…',
    safeError: 'Não foi possível concluir esta captura. Nada financeiro foi lançado. Tente novamente.',
    invalidImage: 'Escolha uma imagem JPEG, PNG, WebP ou HEIC dentro do limite permitido.',
    accessDenied: 'Você não tem permissão para capturar documentos nesta igreja.',
    noPosting: 'A captura não cria movimentação, lançamento ou alteração de saldo.',
    back: 'Voltar',
    reviewTitle: 'Conferir Folha Count',
    reviewSubtitle: 'Compare cada campo com a imagem. Campo ilegível deve permanecer marcado como ilegível — nunca como zero.',
    originalEvidence: 'Evidência original',
    normalizedEvidence: 'Imagem de conferência',
    hiddenTitle: 'Valores protegidos durante a contagem cega',
    hiddenBody: 'A imagem e os valores desta folha ficam ocultos enquanto outra contagem precisa permanecer independente.',
    duplicateTitle: 'Esta foto já foi enviada',
    duplicateBody: 'Encontramos o mesmo arquivo anteriormente. Use a captura original para evitar registros paralelos.',
    openOriginal: 'Abrir captura original',
    saveReview: 'Salvar conferência',
    saving: 'Salvando conferência…',
    saved: 'Conferência salva',
    unreadable: 'Ilegível',
    amount: 'Valor',
    unresolvedHint: 'A leitura automática ainda não confirmou este campo. Digite somente o que você consegue conferir na imagem.',
    fields: { tithe: 'Dízimos', offering: 'Ofertas', other_income: 'Outras entradas', pix: 'Pix' },
    allFieldsRequired: 'Informe um valor ou marque como ilegível em todos os campos.',
    geometryAuto: 'A folha foi alinhada automaticamente com alta confiança.',
    geometryManual: 'A perspectiva foi ajustada pelos cantos que você confirmou.',
    geometryFullFrame: 'A imagem inteira foi confirmada para a conferência.',
    geometryNeedsReview: 'Não conseguimos confirmar as bordas da folha com segurança. Ajuste os quatro cantos ou confirme que a foto já está enquadrada.',
    geometryManualTitle: 'Ajustar cantos da folha',
    geometryManualHint: 'Arraste os quatro pontos até os cantos do papel. Nenhum valor financeiro é lido nesta etapa.',
    applyCorners: 'Aplicar perspectiva',
    useFullFrame: 'Usar imagem inteira',
    adjustCorners: 'Ajustar cantos',
    rotateLeft: 'Girar para a esquerda',
    rotateRight: 'Girar para a direita',
    geometryApplying: 'Corrigindo perspectiva…',
    geometryInvalid: 'Os quatro cantos precisam formar uma folha válida sem cruzamentos.',
    inspectField: 'Ver trecho',
    inspectRegionTitle: 'Trecho da evidência',
    fullImage: 'Ver imagem inteira',
  },
  EN: {
    title: 'Capture Count Sheet',
    subtitle: 'Photograph or choose the completed sheet. The original is preserved and review remains human.',
    choosePhoto: 'Choose photo',
    camera: 'Use camera',
    replace: 'Replace image',
    processing: 'Preparing image…',
    detectedQr: 'Sheet identified by QR',
    manualReference: 'Sheet reference',
    manualReferenceHint: 'If the QR is not recognized, enter the cpf_… reference printed on the sheet.',
    upload: 'Send for review',
    uploading: 'Uploading securely…',
    safeError: 'This capture could not be completed. Nothing financial was posted. Try again.',
    invalidImage: 'Choose a JPEG, PNG, WebP or HEIC image within the allowed size.',
    accessDenied: 'You do not have permission to capture documents for this church.',
    noPosting: 'Capture does not create a transaction, posting or balance change.',
    back: 'Back',
    reviewTitle: 'Review Count Sheet',
    reviewSubtitle: 'Compare every field with the image. An unreadable field must stay unreadable — never be invented as zero.',
    originalEvidence: 'Original evidence',
    normalizedEvidence: 'Review image',
    hiddenTitle: 'Values protected during blind count',
    hiddenBody: 'This sheet image and values stay hidden while another count must remain independent.',
    duplicateTitle: 'This photo was already uploaded',
    duplicateBody: 'We found the exact same file earlier. Use the original capture to avoid parallel records.',
    openOriginal: 'Open original capture',
    saveReview: 'Save review',
    saving: 'Saving review…',
    saved: 'Review saved',
    unreadable: 'Unreadable',
    amount: 'Amount',
    unresolvedHint: 'Automatic reading has not confirmed this field yet. Enter only what you can verify in the image.',
    fields: { tithe: 'Tithes', offering: 'Offerings', other_income: 'Other income', pix: 'Pix' },
    allFieldsRequired: 'Enter an amount or mark every field as unreadable.',
    geometryAuto: 'The sheet was aligned automatically with high confidence.',
    geometryManual: 'Perspective was adjusted using the corners you confirmed.',
    geometryFullFrame: 'The full image was confirmed for review.',
    geometryNeedsReview: 'We could not confirm the sheet edges safely. Adjust the four corners or confirm the photo is already framed.',
    geometryManualTitle: 'Adjust sheet corners',
    geometryManualHint: 'Drag the four points to the paper corners. No financial value is read at this step.',
    applyCorners: 'Apply perspective',
    useFullFrame: 'Use full image',
    adjustCorners: 'Adjust corners',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
    geometryApplying: 'Correcting perspective…',
    geometryInvalid: 'The four corners must form a valid non-crossing sheet.',
    inspectField: 'View region',
    inspectRegionTitle: 'Evidence region',
    fullImage: 'View full image',
  },
  ES: {
    title: 'Capturar Hoja Count',
    subtitle: 'Fotografía o elige la hoja completada. El original se conserva y la revisión sigue siendo humana.',
    choosePhoto: 'Elegir foto',
    camera: 'Usar cámara',
    replace: 'Cambiar imagen',
    processing: 'Preparando imagen…',
    detectedQr: 'Hoja identificada por QR',
    manualReference: 'Referencia de la hoja',
    manualReferenceHint: 'Si el QR no se reconoce, escribe la referencia cpf_… impresa en la hoja.',
    upload: 'Enviar para revisión',
    uploading: 'Enviando de forma segura…',
    safeError: 'No fue posible completar esta captura. No se registró nada financiero. Inténtalo de nuevo.',
    invalidImage: 'Elige una imagen JPEG, PNG, WebP o HEIC dentro del límite permitido.',
    accessDenied: 'No tienes permiso para capturar documentos de esta iglesia.',
    noPosting: 'La captura no crea movimiento, asiento ni cambio de saldo.',
    back: 'Volver',
    reviewTitle: 'Revisar Hoja Count',
    reviewSubtitle: 'Compara cada campo con la imagen. Un campo ilegible debe seguir como ilegible — nunca inventarse como cero.',
    originalEvidence: 'Evidencia original',
    normalizedEvidence: 'Imagen de revisión',
    hiddenTitle: 'Valores protegidos durante el conteo ciego',
    hiddenBody: 'La imagen y los valores de esta hoja quedan ocultos mientras otro conteo debe permanecer independiente.',
    duplicateTitle: 'Esta foto ya fue enviada',
    duplicateBody: 'Encontramos exactamente el mismo archivo antes. Usa la captura original para evitar registros paralelos.',
    openOriginal: 'Abrir captura original',
    saveReview: 'Guardar revisión',
    saving: 'Guardando revisión…',
    saved: 'Revisión guardada',
    unreadable: 'Ilegible',
    amount: 'Valor',
    unresolvedHint: 'La lectura automática aún no confirmó este campo. Escribe solo lo que puedes verificar en la imagen.',
    fields: { tithe: 'Diezmos', offering: 'Ofrendas', other_income: 'Otros ingresos', pix: 'Pix' },
    allFieldsRequired: 'Ingresa un valor o marca todos los campos como ilegibles.',
    geometryAuto: 'La hoja se alineó automáticamente con alta confianza.',
    geometryManual: 'La perspectiva se ajustó usando las esquinas que confirmaste.',
    geometryFullFrame: 'La imagen completa fue confirmada para la revisión.',
    geometryNeedsReview: 'No pudimos confirmar los bordes de la hoja con seguridad. Ajusta las cuatro esquinas o confirma que la foto ya está encuadrada.',
    geometryManualTitle: 'Ajustar esquinas de la hoja',
    geometryManualHint: 'Arrastra los cuatro puntos hasta las esquinas del papel. En este paso no se lee ningún valor financiero.',
    applyCorners: 'Aplicar perspectiva',
    useFullFrame: 'Usar imagen completa',
    adjustCorners: 'Ajustar esquinas',
    rotateLeft: 'Girar a la izquierda',
    rotateRight: 'Girar a la derecha',
    geometryApplying: 'Corrigiendo perspectiva…',
    geometryInvalid: 'Las cuatro esquinas deben formar una hoja válida sin cruces.',
    inspectField: 'Ver región',
    inspectRegionTitle: 'Región de evidencia',
    fullImage: 'Ver imagen completa',
  },
};
