import type { Language } from '@/src/contexts/LanguageContext';

export const UNIVERSAL_CAPTURE_COPY: Record<Language, Record<string, string>> = {
  PT: {
    title: 'Capturar',
    subtitle: 'Envie um comprovante ou documento financeiro.',
    camera: 'Usar câmera',
    photo: 'Escolher foto',
    file: 'Escolher arquivo',
    clipboard: 'Colar da área de transferência',
    preview: 'Confira o arquivo',
    validate: 'Enviar arquivo',
    validating: 'Validando…',
    change: 'Trocar arquivo',
    retry: 'Tentar novamente',
    accepted: 'Arquivo recebido',
    duplicate: 'Já recebemos este comprovante',
    unsupported: 'Este tipo de arquivo ainda não é aceito',
    too_large: 'O arquivo é muito grande. Escolha um de até 10 MB.',
    corrupt: 'Não conseguimos ler este arquivo. Tente novamente.',
    recoverable_error: 'Não foi possível enviar agora. Você pode tentar novamente sem escolher o arquivo outra vez.',
    again: 'Enviar outro',
    noEntity: 'Escolha uma entidade financeira para continuar.',
    noCapability: 'Você não tem permissão para enviar comprovantes nesta entidade.',
    clipboardEmpty: 'Nenhuma imagem ou arquivo foi encontrado para colar.',
    privacy: 'O arquivo será guardado como evidência. Nenhum lançamento será criado automaticamente.',
    entity: 'Entidade financeira',
    contextChanged: 'A organização ou entidade financeira mudou. Os itens pendentes foram removidos para evitar enviar ao livro errado.',
    batchTitle: 'Documentos para analisar',
    batchSubtitle: 'Cada arquivo será preservado e analisado separadamente. Uma falha não interrompe os outros.',
    batchLimit: 'Você pode enviar até 20 documentos por vez.',
    addMore: 'Adicionar mais',
    processAll: 'Enviar e analisar',
    processingBatch: 'Processando documentos…',
    queued: 'Aguardando',
    uploading: 'Enviando',
    analyzing: 'Analisando',
    ready: 'Análise pronta',
    analysisUnavailable: 'Documento salvo · análise pendente',
    openAnalysis: 'Conferir análise',
    remove: 'Remover',
    clearFinished: 'Limpar concluídos',
    batchReady: 'Prontos para conferir',
    batchDuplicate: 'Duplicados',
    batchNeedsAttention: 'Precisam de atenção',
    batchPending: 'Pendentes',
    itemError: 'Falha neste documento',
    itemRetry: 'Tentar este novamente',
    maxBatchReached: 'O limite é de 20 documentos por lote. Os demais não foram adicionados.',
    multipleHint: 'Você pode escolher várias fotos ou arquivos de uma vez.',
    preservedAfterAnalysisError: 'O original foi salvo com segurança. Você pode abrir o Inbox ou tentar a análise novamente.',
    openInbox: 'Abrir Inbox',
    privacyBatch: 'A IA apenas prepara sugestões. Nenhum documento é lançado, aprovado ou contabilizado automaticamente.',
  },
  EN: {
    title: 'Capture',
    subtitle: 'Send a receipt or financial document.',
    camera: 'Use camera',
    photo: 'Choose photo',
    file: 'Choose file',
    clipboard: 'Paste from clipboard',
    preview: 'Review the file',
    validate: 'Send file',
    validating: 'Validating…',
    change: 'Choose another',
    retry: 'Try again',
    accepted: 'File received',
    duplicate: 'We already received this receipt',
    unsupported: 'This file type is not supported yet',
    too_large: 'This file is too large. Choose one up to 10 MB.',
    corrupt: 'We could not read this file. Try again.',
    recoverable_error: 'We could not send it right now. You can try again without choosing the file again.',
    again: 'Send another',
    noEntity: 'Choose a financial entity to continue.',
    noCapability: 'You do not have permission to send receipts for this entity.',
    clipboardEmpty: 'No image or file was available to paste.',
    privacy: 'The file will be kept as evidence. No entry will be created automatically.',
    entity: 'Financial entity',
    contextChanged: 'The organization or financial entity changed. Pending items were removed so they cannot be sent to the wrong ledger.',
    batchTitle: 'Documents to analyze',
    batchSubtitle: 'Each file is preserved and analyzed separately. One failure does not stop the others.',
    batchLimit: 'You can send up to 20 documents at a time.',
    addMore: 'Add more',
    processAll: 'Send and analyze',
    processingBatch: 'Processing documents…',
    queued: 'Waiting',
    uploading: 'Uploading',
    analyzing: 'Analyzing',
    ready: 'Analysis ready',
    analysisUnavailable: 'Document saved · analysis pending',
    openAnalysis: 'Review analysis',
    remove: 'Remove',
    clearFinished: 'Clear finished',
    batchReady: 'Ready to review',
    batchDuplicate: 'Duplicates',
    batchNeedsAttention: 'Need attention',
    batchPending: 'Pending',
    itemError: 'This document failed',
    itemRetry: 'Try this one again',
    maxBatchReached: 'The batch limit is 20 documents. Extra files were not added.',
    multipleHint: 'You can choose several photos or files at once.',
    preservedAfterAnalysisError: 'The original was saved safely. You can open Inbox or retry the analysis.',
    openInbox: 'Open Inbox',
    privacyBatch: 'AI only prepares suggestions. No document is posted, approved, or accounted for automatically.',
  },
  ES: {
    title: 'Capturar',
    subtitle: 'Envía un comprobante o documento financiero.',
    camera: 'Usar cámara',
    photo: 'Elegir foto',
    file: 'Elegir archivo',
    clipboard: 'Pegar del portapapeles',
    preview: 'Revisa el archivo',
    validate: 'Enviar archivo',
    validating: 'Validando…',
    change: 'Cambiar archivo',
    retry: 'Intentar de nuevo',
    accepted: 'Archivo recibido',
    duplicate: 'Ya recibimos este comprobante',
    unsupported: 'Este tipo de archivo aún no es compatible',
    too_large: 'El archivo es demasiado grande. Elige uno de hasta 10 MB.',
    corrupt: 'No pudimos leer este archivo. Inténtalo de nuevo.',
    recoverable_error: 'No pudimos enviarlo ahora. Puedes intentarlo de nuevo sin elegir el archivo otra vez.',
    again: 'Enviar otro',
    noEntity: 'Elige una entidad financiera para continuar.',
    noCapability: 'No tienes permiso para enviar comprobantes en esta entidad.',
    clipboardEmpty: 'No se encontró ninguna imagen o archivo para pegar.',
    privacy: 'El archivo se guardará como evidencia. No se creará ningún asiento automáticamente.',
    entity: 'Entidad financiera',
    contextChanged: 'La organización o entidad financiera cambió. Los elementos pendientes fueron eliminados para evitar enviarlos al libro equivocado.',
    batchTitle: 'Documentos para analizar',
    batchSubtitle: 'Cada archivo se preserva y analiza por separado. Una falla no interrumpe los demás.',
    batchLimit: 'Puedes enviar hasta 20 documentos por vez.',
    addMore: 'Agregar más',
    processAll: 'Enviar y analizar',
    processingBatch: 'Procesando documentos…',
    queued: 'En espera',
    uploading: 'Enviando',
    analyzing: 'Analizando',
    ready: 'Análisis listo',
    analysisUnavailable: 'Documento guardado · análisis pendiente',
    openAnalysis: 'Revisar análisis',
    remove: 'Eliminar',
    clearFinished: 'Limpiar finalizados',
    batchReady: 'Listos para revisar',
    batchDuplicate: 'Duplicados',
    batchNeedsAttention: 'Requieren atención',
    batchPending: 'Pendientes',
    itemError: 'Falló este documento',
    itemRetry: 'Intentar este nuevamente',
    maxBatchReached: 'El límite es de 20 documentos por lote. Los demás no fueron agregados.',
    multipleHint: 'Puedes elegir varias fotos o archivos a la vez.',
    preservedAfterAnalysisError: 'El original fue guardado de forma segura. Puedes abrir el Inbox o intentar el análisis nuevamente.',
    openInbox: 'Abrir Inbox',
    privacyBatch: 'La IA solo prepara sugerencias. Ningún documento se contabiliza, aprueba o registra automáticamente.',
  },
};
