import type { Language } from '@/src/contexts/LanguageContext';

export const UNIVERSAL_CAPTURE_COPY: Record<Language, Record<string, string>> = {
  PT: {
    title: 'Capturar',
    subtitle: 'Envie um comprovante ou documento financeiro.',
    camera: 'Usar câmera',
    photo: 'Escolher foto',
    file: 'Escolher arquivo',
    clipboard: 'Colar da área de transferência',
    preview: 'Confira o arquivo',
    validate: 'Enviar arquivo',
    validating: 'Validando…',
    change: 'Trocar arquivo',
    accepted: 'Arquivo recebido',
    duplicate: 'Já recebemos este comprovante',
    unsupported: 'Este tipo de arquivo ainda não é aceito',
    too_large: 'O arquivo é muito grande. Escolha um de até 10 MB.',
    corrupt: 'Não conseguimos ler este arquivo. Tente novamente.',
    recoverable_error: 'Não foi possível enviar agora. Tente novamente.',
    again: 'Enviar outro',
    noEntity: 'Escolha uma entidade financeira para continuar.',
    noCapability: 'Você não tem permissão para enviar comprovantes nesta entidade.',
    clipboardEmpty: 'Nenhuma imagem ou arquivo foi encontrado para colar.',
    privacy: 'O arquivo será guardado como evidência. Nenhum lançamento será criado automaticamente.',
    entity: 'Entidade financeira',
    contextChanged: 'A organização ou entidade financeira mudou. Escolha o arquivo novamente para evitar enviar ao livro errado.',
  },
  EN: {
    title: 'Capture',
    subtitle: 'Send a receipt or financial document.',
    camera: 'Use camera',
    photo: 'Choose photo',
    file: 'Choose file',
    clipboard: 'Paste from clipboard',
    preview: 'Review the file',
    validate: 'Send file',
    validating: 'Validating…',
    change: 'Choose another',
    accepted: 'File received',
    duplicate: 'We already received this receipt',
    unsupported: 'This file type is not supported yet',
    too_large: 'This file is too large. Choose one up to 10 MB.',
    corrupt: 'We could not read this file. Try again.',
    recoverable_error: 'We could not send it right now. Try again.',
    again: 'Send another',
    noEntity: 'Choose a financial entity to continue.',
    noCapability: 'You do not have permission to send receipts for this entity.',
    clipboardEmpty: 'No image or file was available to paste.',
    privacy: 'The file will be kept as evidence. No entry will be created automatically.',
    entity: 'Financial entity',
    contextChanged: 'The organization or financial entity changed. Choose the file again so it cannot be sent to the wrong ledger.',
  },
  ES: {
    title: 'Capturar',
    subtitle: 'Envía un comprobante o documento financiero.',
    camera: 'Usar cámara',
    photo: 'Elegir foto',
    file: 'Elegir archivo',
    clipboard: 'Pegar del portapapeles',
    preview: 'Revisa el archivo',
    validate: 'Enviar archivo',
    validating: 'Validando…',
    change: 'Cambiar archivo',
    accepted: 'Archivo recibido',
    duplicate: 'Ya recibimos este comprobante',
    unsupported: 'Este tipo de archivo aún no es compatible',
    too_large: 'El archivo es demasiado grande. Elige uno de hasta 10 MB.',
    corrupt: 'No pudimos leer este archivo. Inténtalo de nuevo.',
    recoverable_error: 'No pudimos enviarlo ahora. Inténtalo de nuevo.',
    again: 'Enviar otro',
    noEntity: 'Elige una entidad financiera para continuar.',
    noCapability: 'No tienes permiso para enviar comprobantes en esta entidad.',
    clipboardEmpty: 'No se encontró ninguna imagen o archivo para pegar.',
    privacy: 'El archivo se guardará como evidencia. No se creará ningún asiento automáticamente.',
    entity: 'Entidad financiera',
    contextChanged: 'La organización o entidad financiera cambió. Elige el archivo de nuevo para evitar enviarlo al libro equivocado.',
  },
};
