export const DOCUMENT_ANALYSIS_COPY = {
  PT: {
    title: 'Leitura inteligente do documento',
    subtitle: 'O NestFinance lê o comprovante e prepara uma proposta. Você confirma antes de existir qualquer rascunho financeiro.',
    analyze: 'Analisar documento',
    analyzing: 'Lendo documento…',
    retry: 'Tentar novamente',
    unavailableTitle: 'A leitura inteligente não ficou disponível',
    unavailableBody: 'O documento continua salvo e intacto. Você pode tentar novamente ou lançar manualmente.',
    suggestion: 'Sugestão',
    expense: 'Saída',
    income: 'Entrada',
    unknown: 'Não identificado',
    amount: 'Valor',
    date: 'Data',
    counterparty: 'Fornecedor / pessoa / origem',
    description: 'Sobre o que é',
    category: 'Categoria sugerida',
    paymentMethod: 'Forma de pagamento sugerida',
    issuerTaxId: 'CNPJ do emitente',
    recipientTaxId: 'CNPJ do destinatário/consumidor',
    payerTaxId: 'CNPJ do pagador',
    payeeTaxId: 'CNPJ do beneficiário',
    documentNumber: 'Nº do documento',
    dueDate: 'Vencimento',
    settlement: 'Situação do pagamento',
    settledPaid: 'Pago / concluído',
    settledUnpaid: 'Ainda não pago',
    settledUnknown: 'Não foi possível confirmar',
    currency: 'Moeda',
    noValue: 'Não identificado',
    taxMatch: 'O CNPJ desta igreja foi identificado no documento',
    taxAbsent: 'O documento não traz um CNPJ da igreja em um papel verificável',
    taxUncertain: 'Não foi possível confirmar com segurança o CNPJ desta igreja no documento',
    taxNotConfigured: 'Esta entidade não tem um CNPJ válido disponível para comparação',
    taxMismatch: 'O CNPJ no papel esperado para esta igreja é diferente',
    taxMismatchBody: 'O NestFinance bloqueou este rascunho nesta entidade. Confira os papéis do documento ou troque para a igreja correta.',
    multipleDocs: 'Este arquivo parece conter mais de um documento',
    multipleDocsBody: 'Para manter cada lançamento e comprovante rastreáveis, envie cada documento separadamente.',
    unpaidTitle: 'Este documento não comprova que houve pagamento',
    unpaidBody: 'Conta, fatura, boleto ou cobrança ainda em aberto não deve virar saída de caixa. Use o lançamento manual quando o pagamento realmente ocorrer.',
    currencyTitle: 'A moeda não é BRL',
    currencyBody: 'O financeiro atual trabalha em reais neste fluxo. O documento foi preservado, mas este rascunho não será criado automaticamente.',
    unsupportedKindTitle: 'Este documento não representa uma entrada ou saída simples',
    unsupportedKindBody: 'Transferências internas, extratos e documentos sem um evento financeiro único devem seguir o fluxo apropriado, sem serem forçados a uma entrada ou saída.',
    acknowledgeTax: 'Conferi o documento e quero continuar mesmo sem uma confirmação automática do CNPJ da igreja.',
    createDraft: 'Criar rascunho e revisar',
    creatingDraft: 'Criando rascunho…',
    draftBody: 'O comprovante original será anexado. O rascunho não é postagem e não altera saldo.',
    draftError: 'Não foi possível criar o rascunho. O documento original continua preservado.',
    required: 'Confira natureza, valor e data antes de criar o rascunho.',
    sourceNote: 'A análise é assistida por IA e pode errar. Valores jurídicos e contábeis só são assumidos após sua confirmação.',
    categoryPending: 'Definir depois no rascunho',
    paymentPending: 'Definir depois no rascunho',
  },
  EN: {
    title: 'Smart document reading',
    subtitle: 'NestFinance reads the evidence and prepares a proposal. You confirm it before any financial draft exists.',
    analyze: 'Analyze document',
    analyzing: 'Reading document…',
    retry: 'Try again',
    unavailableTitle: 'Smart reading is not available right now',
    unavailableBody: 'The document remains saved and intact. You can retry or enter it manually.',
    suggestion: 'Suggestion',
    expense: 'Expense',
    income: 'Income',
    unknown: 'Not identified',
    amount: 'Amount',
    date: 'Date',
    counterparty: 'Supplier / person / source',
    description: 'What it is for',
    category: 'Suggested category',
    paymentMethod: 'Suggested payment method',
    issuerTaxId: 'Issuer tax ID',
    recipientTaxId: 'Customer/recipient tax ID',
    payerTaxId: 'Payer tax ID',
    payeeTaxId: 'Payee tax ID',
    documentNumber: 'Document no.',
    dueDate: 'Due date',
    settlement: 'Payment status',
    settledPaid: 'Paid / completed',
    settledUnpaid: 'Not paid yet',
    settledUnknown: 'Could not confirm',
    currency: 'Currency',
    noValue: 'Not identified',
    taxMatch: 'This church tax ID was identified in the document',
    taxAbsent: 'The document does not show the church tax ID in a verifiable role',
    taxUncertain: 'The church tax ID could not be confirmed safely in this document',
    taxNotConfigured: 'This entity has no valid tax ID available for comparison',
    taxMismatch: 'The tax ID in the role expected for this church is different',
    taxMismatchBody: 'NestFinance blocked this draft in the current entity. Check the document roles or switch to the correct church.',
    multipleDocs: 'This file appears to contain more than one document',
    multipleDocsBody: 'To keep each transaction and evidence traceable, send each document separately.',
    unpaidTitle: 'This document does not prove payment happened',
    unpaidBody: 'An unpaid bill, invoice, bank slip or charge must not become a cash expense. Use the appropriate transaction flow when payment actually happens.',
    currencyTitle: 'The currency is not BRL',
    currencyBody: 'This finance flow currently records Brazilian reais. The document is preserved, but an automatic draft will not be created.',
    unsupportedKindTitle: 'This document is not a simple income or expense event',
    unsupportedKindBody: 'Internal transfers, statements and documents without one clear financial event must use the appropriate flow instead of being forced into income or expense.',
    acknowledgeTax: 'I checked the document and want to continue even without an automatic church tax-ID confirmation.',
    createDraft: 'Create draft and review',
    creatingDraft: 'Creating draft…',
    draftBody: 'The preserved original will be attached. A draft is not a posting and does not change balances.',
    draftError: 'The draft could not be created. The original document remains preserved.',
    required: 'Confirm direction, amount and date before creating the draft.',
    sourceNote: 'The analysis is AI-assisted and may be wrong. Legal and accounting values are only accepted after your confirmation.',
    categoryPending: 'Set later in the draft',
    paymentPending: 'Set later in the draft',
  },
  ES: {
    title: 'Lectura inteligente del documento',
    subtitle: 'NestFinance lee el comprobante y prepara una propuesta. Tú la confirmas antes de que exista cualquier borrador financiero.',
    analyze: 'Analizar documento',
    analyzing: 'Leyendo documento…',
    retry: 'Intentar de nuevo',
    unavailableTitle: 'La lectura inteligente no está disponible ahora',
    unavailableBody: 'El documento continúa guardado e intacto. Puedes intentarlo de nuevo o registrarlo manualmente.',
    suggestion: 'Sugerencia',
    expense: 'Salida',
    income: 'Entrada',
    unknown: 'No identificado',
    amount: 'Importe',
    date: 'Fecha',
    counterparty: 'Proveedor / persona / origen',
    description: 'De qué se trata',
    category: 'Categoría sugerida',
    paymentMethod: 'Forma de pago sugerida',
    issuerTaxId: 'CNPJ del emisor',
    recipientTaxId: 'CNPJ del destinatario/consumidor',
    payerTaxId: 'CNPJ del pagador',
    payeeTaxId: 'CNPJ del beneficiario',
    documentNumber: 'Nº del documento',
    dueDate: 'Vencimiento',
    settlement: 'Situación del pago',
    settledPaid: 'Pagado / concluido',
    settledUnpaid: 'Aún no pagado',
    settledUnknown: 'No fue posible confirmar',
    currency: 'Moneda',
    noValue: 'No identificado',
    taxMatch: 'El CNPJ de esta iglesia fue identificado en el documento',
    taxAbsent: 'El documento no muestra el CNPJ de la iglesia en un rol verificable',
    taxUncertain: 'No fue posible confirmar con seguridad el CNPJ de esta iglesia en el documento',
    taxNotConfigured: 'Esta entidad no tiene un CNPJ válido disponible para comparar',
    taxMismatch: 'El CNPJ en el rol esperado para esta iglesia es diferente',
    taxMismatchBody: 'NestFinance bloqueó este borrador en la entidad actual. Revisa los roles del documento o cambia a la iglesia correcta.',
    multipleDocs: 'Este archivo parece contener más de un documento',
    multipleDocsBody: 'Para mantener cada asiento y comprobante trazable, envía cada documento por separado.',
    unpaidTitle: 'Este documento no demuestra que hubo pago',
    unpaidBody: 'Una cuenta, factura, boleto o cobro aún pendiente no debe convertirse en salida de caja. Usa el flujo adecuado cuando el pago realmente ocurra.',
    currencyTitle: 'La moneda no es BRL',
    currencyBody: 'Este flujo financiero actualmente registra reales brasileños. El documento queda preservado, pero no se creará un borrador automático.',
    unsupportedKindTitle: 'Este documento no representa una entrada o salida simple',
    unsupportedKindBody: 'Transferencias internas, extractos y documentos sin un evento financiero único deben seguir el flujo apropiado, sin forzarlos como entrada o salida.',
    acknowledgeTax: 'Revisé el documento y quiero continuar aunque no haya una confirmación automática del CNPJ de la iglesia.',
    createDraft: 'Crear borrador y revisar',
    creatingDraft: 'Creando borrador…',
    draftBody: 'El original preservado quedará adjunto. Un borrador no contabiliza ni cambia saldos.',
    draftError: 'No fue posible crear el borrador. El documento original continúa preservado.',
    required: 'Confirma naturaleza, importe y fecha antes de crear el borrador.',
    sourceNote: 'El análisis está asistido por IA y puede equivocarse. Los valores jurídicos y contables solo se aceptan después de tu confirmación.',
    categoryPending: 'Definir después en el borrador',
    paymentPending: 'Definir después en el borrador',
  },
} as const;
