export const DOCUMENT_ANALYSIS_COPY = {
  PT: {
    title: 'Leitura inteligente do documento',
    subtitle: 'O NestFinance lê o comprovante e prepara uma proposta. Você confirma antes de existir qualquer rascunho financeiro.',
    analyze: 'Analisar documento',
    analyzing: 'Lendo documento…',
    retry: 'Tentar novamente',
    unavailableTitle: 'A leitura inteligente não ficou disponível',
    unavailableBody: 'O documento continua salvo e intacto. Você pode tentar novamente ou lançar manualmente.',
    suggestion: 'Sugestão',
    expense: 'Saída',
    income: 'Entrada',
    unknown: 'Não identificado',
    amount: 'Valor',
    date: 'Data',
    counterparty: 'Estabelecimento / origem',
    description: 'Sobre o que é',
    category: 'Categoria sugerida',
    paymentMethod: 'Forma de pagamento sugerida',
    issuerTaxId: 'CNPJ do emitente',
    recipientTaxId: 'CNPJ do consumidor/destinatário',
    noValue: 'Não identificado',
    taxMatch: 'CNPJ confere com esta igreja',
    taxAbsent: 'O documento não informa CNPJ do consumidor/destinatário',
    taxUncertain: 'Não foi possível confirmar o CNPJ do consumidor/destinatário',
    taxNotConfigured: 'Esta entidade não tem um CNPJ válido disponível para comparação',
    taxMismatch: 'O CNPJ do consumidor/destinatário é diferente do CNPJ desta igreja',
    taxMismatchBody: 'Não crie o rascunho nesta entidade. Confira o documento ou troque para a igreja correta.',
    multipleDocs: 'Este arquivo parece conter mais de um documento',
    multipleDocsBody: 'Para manter cada lançamento e comprovante rastreáveis, envie cada documento separadamente.',
    acknowledgeTax: 'Conferi o documento e quero continuar mesmo sem uma confirmação automática do CNPJ da igreja.',
    createDraft: 'Criar rascunho e revisar',
    creatingDraft: 'Criando rascunho…',
    draftBody: 'O comprovante original será anexado. O rascunho não é postagem e não altera saldo.',
    draftError: 'Não foi possível criar o rascunho. O documento original continua preservado.',
    required: 'Confira natureza, valor e data antes de criar o rascunho.',
    sourceNote: 'A análise é assistida por IA e pode errar. Valores jurídicos e contábeis só são assumidos após sua confirmação.',
    categoryPending: 'Definir depois no rascunho',
    paymentPending: 'Definir depois no rascunho',
  },
  EN: {
    title: 'Smart document reading',
    subtitle: 'NestFinance reads the evidence and prepares a proposal. You confirm it before any financial draft exists.',
    analyze: 'Analyze document',
    analyzing: 'Reading document…',
    retry: 'Try again',
    unavailableTitle: 'Smart reading is not available right now',
    unavailableBody: 'The document remains saved and intact. You can retry or enter it manually.',
    suggestion: 'Suggestion',
    expense: 'Expense',
    income: 'Income',
    unknown: 'Not identified',
    amount: 'Amount',
    date: 'Date',
    counterparty: 'Merchant / source',
    description: 'What it is for',
    category: 'Suggested category',
    paymentMethod: 'Suggested payment method',
    issuerTaxId: 'Issuer tax ID',
    recipientTaxId: 'Customer/recipient tax ID',
    noValue: 'Not identified',
    taxMatch: 'Tax ID matches this church',
    taxAbsent: 'The document does not show a customer/recipient tax ID',
    taxUncertain: 'The customer/recipient tax ID could not be confirmed',
    taxNotConfigured: 'This entity has no valid tax ID available for comparison',
    taxMismatch: 'The customer/recipient tax ID differs from this church',
    taxMismatchBody: 'Do not create this draft in the current entity. Check the document or switch to the correct church.',
    multipleDocs: 'This file appears to contain more than one document',
    multipleDocsBody: 'To keep each transaction and evidence traceable, send each document separately.',
    acknowledgeTax: 'I checked the document and want to continue even without an automatic church tax-ID confirmation.',
    createDraft: 'Create draft and review',
    creatingDraft: 'Creating draft…',
    draftBody: 'The preserved original will be attached. A draft is not a posting and does not change balances.',
    draftError: 'The draft could not be created. The original document remains preserved.',
    required: 'Confirm direction, amount and date before creating the draft.',
    sourceNote: 'The analysis is AI-assisted and may be wrong. Legal and accounting values are only accepted after your confirmation.',
    categoryPending: 'Set later in the draft',
    paymentPending: 'Set later in the draft',
  },
  ES: {
    title: 'Lectura inteligente del documento',
    subtitle: 'NestFinance lee el comprobante y prepara una propuesta. Tú la confirmas antes de que exista cualquier borrador financiero.',
    analyze: 'Analizar documento',
    analyzing: 'Leyendo documento…',
    retry: 'Intentar de nuevo',
    unavailableTitle: 'La lectura inteligente no está disponible ahora',
    unavailableBody: 'El documento continúa guardado e intacto. Puedes intentarlo de nuevo o registrarlo manualmente.',
    suggestion: 'Sugerencia',
    expense: 'Salida',
    income: 'Entrada',
    unknown: 'No identificado',
    amount: 'Importe',
    date: 'Fecha',
    counterparty: 'Establecimiento / origen',
    description: 'De qué se trata',
    category: 'Categoría sugerida',
    paymentMethod: 'Forma de pago sugerida',
    issuerTaxId: 'CNPJ del emisor',
    recipientTaxId: 'CNPJ del consumidor/destinatario',
    noValue: 'No identificado',
    taxMatch: 'El CNPJ coincide con esta iglesia',
    taxAbsent: 'El documento no informa el CNPJ del consumidor/destinatario',
    taxUncertain: 'No fue posible confirmar el CNPJ del consumidor/destinatario',
    taxNotConfigured: 'Esta entidad no tiene un CNPJ válido disponible para comparar',
    taxMismatch: 'El CNPJ del consumidor/destinatario es diferente al de esta iglesia',
    taxMismatchBody: 'No crees el borrador en esta entidad. Revisa el documento o cambia a la iglesia correcta.',
    multipleDocs: 'Este archivo parece contener más de un documento',
    multipleDocsBody: 'Para mantener cada asiento y comprobante trazable, envía cada documento por separado.',
    acknowledgeTax: 'Revisé el documento y quiero continuar aunque no haya una confirmación automática del CNPJ de la iglesia.',
    createDraft: 'Crear borrador y revisar',
    creatingDraft: 'Creando borrador…',
    draftBody: 'El original preservado quedará adjunto. Un borrador no contabiliza ni cambia saldos.',
    draftError: 'No fue posible crear el borrador. El documento original continúa preservado.',
    required: 'Confirma naturaleza, importe y fecha antes de crear el borrador.',
    sourceNote: 'El análisis está asistido por IA y puede equivocarse. Los valores jurídicos y contables solo se aceptan después de tu confirmación.',
    categoryPending: 'Definir después en el borrador',
    paymentPending: 'Definir después en el borrador',
  },
} as const;
