export const INBOX_COPY = {
  PT: {
    pageTitle: 'Inbox',
    pageSubtitle: 'Documentos e evidências recebidos nesta entidade financeira. Nenhum lançamento é criado automaticamente.',
    accessDeniedTitle: 'Sem acesso ao Inbox',
    accessDeniedBody: 'Seu acesso atual não permite visualizar os documentos financeiros desta entidade.',
    capture: 'Capturar documento',
    summaryTotal: 'Recebidos',
    summaryAccepted: 'Prontos',
    summaryDuplicate: 'Duplicados',
    summaryAwaiting: 'Envio pendente',
    queueTitle: 'Evidências recentes',
    queueSubtitle: 'Arquivos preservados e validados antes de qualquer uso contábil.',
    accepted: 'Pronto',
    duplicate: 'Duplicado',
    awaitingUpload: 'Envio pendente',
    unknownStatus: 'Estado desconhecido',
    sourceCamera: 'Câmera',
    sourcePhoto: 'Fotos',
    sourceFile: 'Arquivo',
    sourceClipboard: 'Área de transferência',
    sourceUnknown: 'Origem desconhecida',
    receivedAt: 'Recebido',
    validatedAt: 'Validado',
    imageDimensions: 'Dimensões',
    emptyTitle: 'Nenhum documento por aqui ainda',
    emptyBody: 'Quando um comprovante, foto ou PDF for capturado, ele aparecerá aqui sem criar lançamentos automaticamente.',
    errorTitle: 'Não foi possível carregar o Inbox',
    errorBody: 'Tente novamente. Se o problema continuar, o código de suporte abaixo ajuda a localizar a falha.',
    retry: 'Tentar novamente',
    loadMore: 'Carregar mais',
    loading: 'Carregando documentos',
    supportCode: 'Código de suporte',
    back: 'Voltar para Hoje',
    secureMetadata: 'Nesta etapa, o Inbox exibe somente metadados seguros da evidência. O arquivo original continua preservado no armazenamento protegido.',
    unknownFile: 'Documento sem nome',
  },
  EN: {
    pageTitle: 'Inbox',
    pageSubtitle: 'Documents and evidence received for this finance entity. No transaction is created automatically.',
    accessDeniedTitle: 'No access to Inbox',
    accessDeniedBody: 'Your current access does not allow you to view financial documents for this entity.',
    capture: 'Capture document',
    summaryTotal: 'Received',
    summaryAccepted: 'Ready',
    summaryDuplicate: 'Duplicates',
    summaryAwaiting: 'Upload pending',
    queueTitle: 'Recent evidence',
    queueSubtitle: 'Files preserved and validated before any accounting use.',
    accepted: 'Ready',
    duplicate: 'Duplicate',
    awaitingUpload: 'Upload pending',
    unknownStatus: 'Unknown status',
    sourceCamera: 'Camera',
    sourcePhoto: 'Photos',
    sourceFile: 'File',
    sourceClipboard: 'Clipboard',
    sourceUnknown: 'Unknown source',
    receivedAt: 'Received',
    validatedAt: 'Validated',
    imageDimensions: 'Dimensions',
    emptyTitle: 'No documents here yet',
    emptyBody: 'When a receipt, photo, or PDF is captured, it will appear here without creating transactions automatically.',
    errorTitle: 'Inbox could not be loaded',
    errorBody: 'Try again. If the problem continues, the support code below helps locate the failure.',
    retry: 'Try again',
    loadMore: 'Load more',
    loading: 'Loading documents',
    supportCode: 'Support code',
    back: 'Back to Today',
    secureMetadata: 'At this stage, Inbox shows only safe evidence metadata. The original file remains preserved in protected storage.',
    unknownFile: 'Unnamed document',
  },
  ES: {
    pageTitle: 'Inbox',
    pageSubtitle: 'Documentos y evidencias recibidos para esta entidad financiera. No se crea ningún asiento automáticamente.',
    accessDeniedTitle: 'Sin acceso al Inbox',
    accessDeniedBody: 'Tu acceso actual no permite ver los documentos financieros de esta entidad.',
    capture: 'Capturar documento',
    summaryTotal: 'Recibidos',
    summaryAccepted: 'Listos',
    summaryDuplicate: 'Duplicados',
    summaryAwaiting: 'Carga pendiente',
    queueTitle: 'Evidencias recientes',
    queueSubtitle: 'Archivos preservados y validados antes de cualquier uso contable.',
    accepted: 'Listo',
    duplicate: 'Duplicado',
    awaitingUpload: 'Carga pendiente',
    unknownStatus: 'Estado desconocido',
    sourceCamera: 'Cámara',
    sourcePhoto: 'Fotos',
    sourceFile: 'Archivo',
    sourceClipboard: 'Portapapeles',
    sourceUnknown: 'Origen desconocido',
    receivedAt: 'Recibido',
    validatedAt: 'Validado',
    imageDimensions: 'Dimensiones',
    emptyTitle: 'Aún no hay documentos aquí',
    emptyBody: 'Cuando se capture un comprobante, una foto o un PDF, aparecerá aquí sin crear asientos automáticamente.',
    errorTitle: 'No se pudo cargar el Inbox',
    errorBody: 'Inténtalo de nuevo. Si el problema continúa, el código de soporte ayuda a localizar la falla.',
    retry: 'Intentar de nuevo',
    loadMore: 'Cargar más',
    loading: 'Cargando documentos',
    supportCode: 'Código de soporte',
    back: 'Volver a Hoy',
    secureMetadata: 'En esta etapa, el Inbox muestra solo metadatos seguros de la evidencia. El archivo original permanece preservado en el almacenamiento protegido.',
    unknownFile: 'Documento sin nombre',
  },
} as const;
