export const PDF_READINESS_COPY = {
  PT: {
    title: 'Texto do PDF',
    subtitle: 'Verifique se o analisador determinístico detecta sinais de texto digital neste PDF antes de considerar OCR ou IA.',
    action: 'Verificar texto digital',
    loading: 'Verificando…',
    detectedTitle: 'Texto digital detectado',
    detectedBody: 'O analisador determinístico detectou sinais de texto digital no subconjunto suportado. Nenhum OCR, IA ou reconhecimento financeiro foi executado.',
    notDetectedTitle: 'Texto digital não detectado',
    notDetectedBody: 'O analisador determinístico não encontrou texto no subconjunto suportado. Isso não prova que o PDF não tenha texto. OCR continua desativado.',
    unknownTitle: 'Não foi possível determinar',
    unknownBody: 'A estrutura deste PDF não permite uma conclusão segura nesta etapa. O NestFinance não tenta adivinhar nem aciona OCR ou IA automaticamente.',
    errorTitle: 'Não foi possível verificar o texto',
    errorBody: 'Tente novamente. Nenhum dado financeiro foi criado ou alterado.',
    retry: 'Tentar novamente',
    privacy: 'Análise somente leitura do original já verificado. Nenhum lançamento financeiro é criado.',
    supportCode: 'Código de suporte',
  },
  EN: {
    title: 'PDF text',
    subtitle: 'Check whether the deterministic analyzer detects signs of digital text in this PDF before considering OCR or AI.',
    action: 'Check digital text',
    loading: 'Checking…',
    detectedTitle: 'Digital text detected',
    detectedBody: 'The deterministic analyzer detected signs of digital text in the supported subset. No OCR, AI, or financial recognition was performed.',
    notDetectedTitle: 'Digital text not detected',
    notDetectedBody: 'The deterministic analyzer did not find text in the supported subset. This does not prove that the PDF has no text. OCR remains disabled.',
    unknownTitle: 'Unable to determine',
    unknownBody: 'This PDF structure does not allow a safe conclusion at this stage. NestFinance does not guess or trigger OCR or AI automatically.',
    errorTitle: 'Unable to check PDF text',
    errorBody: 'Try again. No financial data was created or changed.',
    retry: 'Try again',
    privacy: 'Read-only analysis of the already verified original. No financial entry is created.',
    supportCode: 'Support code',
  },
  ES: {
    title: 'Texto del PDF',
    subtitle: 'Verifica si el analizador determinista detecta señales de texto digital en este PDF antes de considerar OCR o IA.',
    action: 'Verificar texto digital',
    loading: 'Verificando…',
    detectedTitle: 'Texto digital detectado',
    detectedBody: 'El analizador determinista detectó señales de texto digital en el subconjunto compatible. No se ejecutó OCR, IA ni reconocimiento financiero.',
    notDetectedTitle: 'Texto digital no detectado',
    notDetectedBody: 'El analizador determinista no encontró texto en el subconjunto compatible. Esto no demuestra que el PDF no tenga texto. OCR permanece desactivado.',
    unknownTitle: 'No fue posible determinarlo',
    unknownBody: 'La estructura de este PDF no permite una conclusión segura en esta etapa. NestFinance no adivina ni activa OCR o IA automáticamente.',
    errorTitle: 'No fue posible verificar el texto',
    errorBody: 'Inténtalo de nuevo. No se creó ni modificó ningún dato financiero.',
    retry: 'Intentar de nuevo',
    privacy: 'Análisis de solo lectura del original ya verificado. No se crea ningún asiento financiero.',
    supportCode: 'Código de soporte',
  },
} as const;
