export const PDF_SIGNALS_COPY = {
  PT: {
    title: 'Sinais determinísticos no texto',
    subtitle: 'Procure padrões explícitos no texto já lido, sem OCR ou IA.',
    action: 'Analisar sinais',
    retry: 'Analisar novamente',
    foundTitle: (count: number) => `${count} ${count === 1 ? 'sinal encontrado' : 'sinais encontrados'}`,
    foundBody: 'São candidatos de revisão, não dados financeiros confirmados. Confira sempre o documento original.',
    emptyTitle: 'Nenhum sinal explícito encontrado',
    emptyBody: 'Isso não prova que o documento não contenha dados relevantes. O NestFinance não adivinha campos ausentes ou ambíguos.',
    inputLimited: 'A leitura disponível foi limitada aos primeiros 100.000 caracteres. Sinais depois desse ponto não foram analisados.',
    candidateLimited: 'A lista atingiu o limite de 100 candidatos. Nenhum candidato adicional foi inferido ou priorizado automaticamente.',
    rawLabel: 'Trecho detectado',
    contextLabel: 'Contexto',
    evidence: {
      validated: 'Validado por regra',
      explicit_label: 'Rótulo explícito',
      pattern_only: 'Somente padrão',
    },
    kinds: {
      cpf: 'CPF',
      cnpj: 'CNPJ',
      date: 'Data',
      money: 'Valor',
      pix_key: 'Chave Pix',
      boleto: 'Boleto / código',
    },
    privacy: 'A análise acontece somente nesta tela, em memória. Os sinais não são salvos, não criam lançamentos e não executam OCR, IA ou alterações financeiras.',
  },
  EN: {
    title: 'Deterministic text signals',
    subtitle: 'Look for explicit patterns in the text already read, without OCR or AI.',
    action: 'Analyze signals',
    retry: 'Analyze again',
    foundTitle: (count: number) => `${count} ${count === 1 ? 'signal found' : 'signals found'}`,
    foundBody: 'These are review candidates, not confirmed financial data. Always check the original document.',
    emptyTitle: 'No explicit signals found',
    emptyBody: 'This does not prove that the document contains no relevant data. NestFinance does not guess missing or ambiguous fields.',
    inputLimited: 'The available read was limited to the first 100,000 characters. Signals after that point were not analyzed.',
    candidateLimited: 'The list reached the 100-candidate limit. No additional candidate was inferred or automatically prioritized.',
    rawLabel: 'Detected excerpt',
    contextLabel: 'Context',
    evidence: {
      validated: 'Rule validated',
      explicit_label: 'Explicit label',
      pattern_only: 'Pattern only',
    },
    kinds: {
      cpf: 'CPF',
      cnpj: 'CNPJ',
      date: 'Date',
      money: 'Amount',
      pix_key: 'Pix key',
      boleto: 'Boleto / code',
    },
    privacy: 'Analysis runs only on this screen, in memory. Signals are not saved, do not create entries, and do not run OCR, AI, or financial changes.',
  },
  ES: {
    title: 'Señales determinísticas en el texto',
    subtitle: 'Busca patrones explícitos en el texto ya leído, sin OCR ni IA.',
    action: 'Analizar señales',
    retry: 'Analizar de nuevo',
    foundTitle: (count: number) => `${count} ${count === 1 ? 'señal encontrada' : 'señales encontradas'}`,
    foundBody: 'Son candidatos para revisión, no datos financieros confirmados. Comprueba siempre el documento original.',
    emptyTitle: 'No se encontraron señales explícitas',
    emptyBody: 'Esto no demuestra que el documento no contenga datos relevantes. NestFinance no adivina campos ausentes o ambiguos.',
    inputLimited: 'La lectura disponible se limitó a los primeros 100.000 caracteres. Las señales posteriores no fueron analizadas.',
    candidateLimited: 'La lista alcanzó el límite de 100 candidatos. No se infirió ni priorizó automáticamente ningún candidato adicional.',
    rawLabel: 'Fragmento detectado',
    contextLabel: 'Contexto',
    evidence: {
      validated: 'Validado por regla',
      explicit_label: 'Etiqueta explícita',
      pattern_only: 'Solo patrón',
    },
    kinds: {
      cpf: 'CPF',
      cnpj: 'CNPJ',
      date: 'Fecha',
      money: 'Importe',
      pix_key: 'Clave Pix',
      boleto: 'Boleto / código',
    },
    privacy: 'El análisis se ejecuta solo en esta pantalla, en memoria. Las señales no se guardan, no crean asientos y no ejecutan OCR, IA ni cambios financieros.',
  },
} as const;
