export const PDF_TEXT_COPY = {
  PT: {
    action: 'Ler texto do PDF',
    loading: 'Lendo…',
    retry: 'Ler novamente',
    extractedTitle: 'Texto nativo extraído',
    extractedBody: 'O NestFinance leu somente a camada de texto já existente neste PDF. Nenhum OCR, IA ou reconhecimento financeiro foi executado.',
    truncated: 'A exibição foi limitada aos primeiros 100.000 caracteres para manter a leitura segura e previsível.',
    metadata: (extractedPages: number, totalPages: number, characters: number) => `${extractedPages} de ${totalPages} páginas · ${characters.toLocaleString('pt-BR')} caracteres`,
    unavailableTitle: 'Leitura nativa indisponível',
    reasons: {
      input_too_large: 'Este PDF ultrapassa o limite de 4 MiB para leitura nativa nesta etapa.',
      encrypted: 'Este PDF está protegido ou criptografado e não será aberto por esta etapa.',
      text_layer_not_detected: 'Não foi encontrada uma camada de texto nativa compatível. OCR continua desativado.',
      structural_preflight_incomplete: 'A estrutura do PDF não passou pelas verificações necessárias para uma leitura segura.',
      page_limit_exceeded: 'Este PDF ultrapassa o limite de 40 páginas para leitura nativa nesta etapa.',
      extraction_empty: 'A camada nativa foi processada, mas não retornou texto legível.',
      parser_error: 'Não foi possível ler este PDF com segurança usando o analisador nativo.',
    },
    errorTitle: 'Não foi possível ler o texto',
    errorBody: 'Tente novamente. Nenhum dado financeiro foi criado ou alterado.',
    tooLarge: 'Este PDF ultrapassa o limite de 4 MiB para leitura nativa.',
    privacy: 'O texto é exibido somente nesta tela e não é salvo pelo NestFinance. Nenhum OCR, IA, lançamento ou alteração financeira é executado.',
    supportCode: 'Código de suporte',
  },
  EN: {
    action: 'Read PDF text',
    loading: 'Reading…',
    retry: 'Read again',
    extractedTitle: 'Native text extracted',
    extractedBody: 'NestFinance read only the text layer already present in this PDF. No OCR, AI, or financial recognition was performed.',
    truncated: 'The display was limited to the first 100,000 characters to keep reading safe and predictable.',
    metadata: (extractedPages: number, totalPages: number, characters: number) => `${extractedPages} of ${totalPages} pages · ${characters.toLocaleString('en-US')} characters`,
    unavailableTitle: 'Native text unavailable',
    reasons: {
      input_too_large: 'This PDF exceeds the 4 MiB native-reading limit for this stage.',
      encrypted: 'This PDF is protected or encrypted and will not be opened by this stage.',
      text_layer_not_detected: 'No compatible native text layer was found. OCR remains disabled.',
      structural_preflight_incomplete: 'The PDF structure did not pass the checks required for safe native reading.',
      page_limit_exceeded: 'This PDF exceeds the 40-page native-reading limit for this stage.',
      extraction_empty: 'The native layer was processed but returned no readable text.',
      parser_error: 'This PDF could not be read safely by the native analyzer.',
    },
    errorTitle: 'Unable to read PDF text',
    errorBody: 'Try again. No financial data was created or changed.',
    tooLarge: 'This PDF exceeds the 4 MiB native-reading limit.',
    privacy: 'Text is shown only on this screen and is not saved by NestFinance. No OCR, AI, financial entry, or financial change is performed.',
    supportCode: 'Support code',
  },
  ES: {
    action: 'Leer texto del PDF',
    loading: 'Leyendo…',
    retry: 'Leer de nuevo',
    extractedTitle: 'Texto nativo extraído',
    extractedBody: 'NestFinance leyó únicamente la capa de texto ya existente en este PDF. No se ejecutó OCR, IA ni reconocimiento financiero.',
    truncated: 'La visualización se limitó a los primeros 100.000 caracteres para mantener una lectura segura y predecible.',
    metadata: (extractedPages: number, totalPages: number, characters: number) => `${extractedPages} de ${totalPages} páginas · ${characters.toLocaleString('es-ES')} caracteres`,
    unavailableTitle: 'Lectura nativa no disponible',
    reasons: {
      input_too_large: 'Este PDF supera el límite de 4 MiB para lectura nativa en esta etapa.',
      encrypted: 'Este PDF está protegido o cifrado y no será abierto por esta etapa.',
      text_layer_not_detected: 'No se encontró una capa de texto nativa compatible. OCR permanece desactivado.',
      structural_preflight_incomplete: 'La estructura del PDF no superó las verificaciones necesarias para una lectura segura.',
      page_limit_exceeded: 'Este PDF supera el límite de 40 páginas para lectura nativa en esta etapa.',
      extraction_empty: 'La capa nativa fue procesada, pero no devolvió texto legible.',
      parser_error: 'No fue posible leer este PDF de forma segura con el analizador nativo.',
    },
    errorTitle: 'No fue posible leer el texto',
    errorBody: 'Inténtalo de nuevo. No se creó ni modificó ningún dato financiero.',
    tooLarge: 'Este PDF supera el límite de 4 MiB para lectura nativa.',
    privacy: 'El texto se muestra solo en esta pantalla y NestFinance no lo guarda. No se ejecuta OCR, IA, asiento ni cambio financiero.',
    supportCode: 'Código de soporte',
  },
} as const;
